export enum CardActionType {
  DEAL_DAMAGE_FORWARD,
  DEAL_DAMAGE_FORWARDS,
  DEAL_DAMAGE_PLAYER,

  INCREASE_COUNTER,
  DECREASE_COUNTER,

  SEND_CARD_TO_BREAK_ZONE,
  SEND_CARD_TO_DECK,
  SEND_CARD_TO_HAND,
  REMOVE_CARD_FROM_GAME,
  INCREASE_POWER,

  INCREASE_DAMAGE_TAKEN,
  INCREASE_DAMAGE_DEALT,
  DECREASE_DAMAGE_TAKEN,
  DECREASE_DAMAGE_DEALT,
}
